"""Generate secure keys for backend configuration."""
import secrets
import base64

print("=" * 80)
print("GENERATING SECURE KEYS FOR BACKEND CONFIGURATION")
print("=" * 80)
print()

# 1. Generate SECRET_KEY for JWT signing
print("1. SECRET_KEY (for JWT token signing)")
print("-" * 80)
secret_key = secrets.token_urlsafe(64)
print(f"SECRET_KEY={secret_key}")
print()
print("   Purpose: Used by FastAPI to sign JWT authentication tokens")
print("   Security: 64-byte URL-safe random string")
print()

# 2. Generate PHI_ENCRYPTION_KEY (32 bytes, base64-encoded)
print("2. PHI_ENCRYPTION_KEY (for encrypting patient data)")
print("-" * 80)
phi_key_bytes = secrets.token_bytes(32)
phi_key_base64 = base64.b64encode(phi_key_bytes).decode('ascii')
print(f"PHI_ENCRYPTION_KEY={phi_key_base64}")
print()
print("   Purpose: Used to encrypt PHI (Protected Health Information)")
print("   Security: 32-byte (256-bit) key, base64-encoded")
print("   Standard: AES-256 encryption key")
print()

# 3. Azure SignalR Connection String
print("3. AZURE_SIGNALR_CONNECTION_STRING")
print("-" * 80)
print("   This requires an Azure SignalR Service instance.")
print()
print("   Options:")
print()
print("   A. TESTING/DEVELOPMENT (Mock):")
print("      Use a fake connection string for local testing:")
print(f"      AZURE_SIGNALR_CONNECTION_STRING=Endpoint=https://test.service.signalr.net;AccessKey={secrets.token_urlsafe(32)};Version=1.0;")
print()
print("   B. PRODUCTION (Real Azure SignalR):")
print("      Steps to get real connection string:")
print("      1. Go to Azure Portal: https://portal.azure.com")
print("      2. Create new 'SignalR Service' resource")
print("      3. Navigate to resource -> Settings -> Keys")
print("      4. Copy 'Connection String' (primary or secondary)")
print()
print("      Format: Endpoint=https://<name>.service.signalr.net;AccessKey=<key>;Version=1.0;")
print()

print("=" * 80)
print("COMPLETE .ENV FILE CONTENT")
print("=" * 80)
print()
print("Copy the following into backend/.env:")
print()
print("-" * 80)
print("# Database Connection (Cloud SQL Proxy)")
print("DATABASE_URL=postgresql+asyncpg://postgres:SmartHandoff%40123@localhost:9000/smarthandoff")
print()
print("# Security Keys (Generated)")
print(f"SECRET_KEY={secret_key}")
print(f"PHI_ENCRYPTION_KEY={phi_key_base64}")
print()
print("# Azure SignalR (Choose option A or B above)")
print(f"AZURE_SIGNALR_CONNECTION_STRING=Endpoint=https://test.service.signalr.net;AccessKey={secrets.token_urlsafe(32)};Version=1.0;")
print()
print("# GCP Configuration")
print("GCP_PROJECT_ID=smarthandoff")
print("GCP_REGION=us-central1")
print()
print("# API Configuration")
print("DEBUG=True")
print("LOG_LEVEL=INFO")
print("API_V1_PREFIX=/api/v1")
print()
print("# JWT Configuration")
print("ALGORITHM=HS256")
print("ACCESS_TOKEN_EXPIRE_MINUTES=30")
print()
print("# Optional: Twilio (for SMS notifications)")
print("# TWILIO_ACCOUNT_SID=your-account-sid")
print("# TWILIO_FROM_NUMBER=+1234567890")
print()
print("# Optional: SendGrid (for email notifications)")
print("# SENDGRID_FROM_EMAIL=noreply@smarthandoff.com")
print("-" * 80)
print()

print("=" * 80)
print("NEXT STEPS")
print("=" * 80)
print()
print("1. Create the .env file:")
print("   cd backend")
print("   notepad .env")
print()
print("2. Paste the configuration above into .env")
print()
print("3. Verify Cloud SQL Proxy is running:")
print("   Check terminal 'cloud-sql-proxy' is active")
print()
print("4. Start the backend API:")
print("   uvicorn app.main:app --reload --host 0.0.0.0 --port 8000")
print()
print("5. Test the API:")
print("   Open browser: http://localhost:8000/docs")
print("   Or: curl http://localhost:8000/metrics")
print()
print("=" * 80)
print()

print("IMPORTANT SECURITY NOTES:")
print("-" * 80)
print("• NEVER commit .env file to git (already in .gitignore)")
print("• Store production keys in GCP Secret Manager")
print("• Rotate keys periodically (every 90 days recommended)")
print("• Use different keys for dev/staging/production")
print()
