"""
PatientInstructionsGenerator — plain-language patient discharge instruction generator.

Produces patient-friendly instructions from the AI discharge summary generated by
DocumentationAgent (US-025). Uses Gemini Flash for cost-efficient generation and
translation (FR-022). Enforces ≤ 6th-grade Flesch-Kincaid reading level (FR-021).

Translation and back-translation quality checking is handled by
PatientInstructionsTranslator (TASK-004).
"""
from __future__ import annotations

import logging
from typing import Optional

from langchain_google_vertexai import ChatVertexAI
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate

from agents.documentation.patient_instructions_schemas import (
    PatientInstructionsContent,
    PatientInstructionsDocument,
    SupportedLanguage,
)
from agents.documentation.language_utils import resolve_patient_language
from agents.documentation.reading_level_scorer import ReadingLevelScorer
from agents.documentation.schemas import DischargeSummarySchema

logger = logging.getLogger(__name__)

# Maximum number of simplification attempts before accepting the best-effort result
_MAX_FK_RETRIES: int = 2

_GENERATION_PROMPT = PromptTemplate.from_template(
    """You are a healthcare educator writing patient discharge instructions.
Write clear, simple instructions that a 6th-grade student can understand.
Use short sentences. Use everyday words. Do NOT use medical jargon.

Here is the medical discharge summary you must convert into patient instructions:

--- DISCHARGE SUMMARY ---
Diagnoses: {diagnoses}
Medications at discharge: {medications}
Procedures: {procedures}
Follow-up instructions: {follow_up}
Warning signs: {warning_signs}
Activity restrictions: {activity_restrictions}
--- END SUMMARY ---

Write patient instructions covering all six areas:
1. Home care instructions
2. Medications (name, dose, when to take, why)
3. Warning signs (when to call the doctor or go to the ER)
4. Follow-up appointments
5. Diet and activity
6. Emergency contact information

{format_instructions}
"""
)


class PatientInstructionsGenerator:
    """
    Generates plain-language patient discharge instructions from a DischargeSummarySchema.

    Enforces FK Grade ≤ 6.0 with up to 2 simplification retries (US-027 Scenario 1).
    Detects patient preferred language from FHIR Patient resource (US-027 Scenario 3 & 4).

    Args:
        project_id: GCP project ID for Vertex AI.
        location: GCP region for Vertex AI endpoint.
    """

    def __init__(self, project_id: str, location: str = "us-central1") -> None:
        # Gemini Flash — cost-efficient for instructions and translation (US-027 Technical Notes)
        self._llm = ChatVertexAI(
            model_name="gemini-1.5-flash",
            project=project_id,
            location=location,
            temperature=0.1,
            max_output_tokens=2048,
            model_kwargs={"response_mime_type": "application/json"},
        )
        self._scorer = ReadingLevelScorer()
        self._parser = PydanticOutputParser(pydantic_object=PatientInstructionsContent)

    async def generate(
        self,
        discharge_summary: DischargeSummarySchema,
        fhir_patient: dict,
    ) -> PatientInstructionsDocument:
        """
        Generate patient instructions and detect language preference.

        Steps:
        1. Resolve patient preferred language from FHIR Patient.communication
        2. Generate English instructions with FK grade enforcement
        3. Build PatientInstructionsDocument (translations populated by TASK-004)

        Args:
            discharge_summary: Structured discharge summary from DocumentationAgent (US-025).
            fhir_patient: Raw FHIR Patient resource dict (from US-017 FHIRClient).

        Returns:
            PatientInstructionsDocument with English content and language metadata.
            Translations field is empty — filled by PatientInstructionsTranslator (TASK-004).
        """
        # Step 1: Resolve language preference
        preferred_lang, is_fallback, requested_lang = resolve_patient_language(fhir_patient)

        # Step 2: Generate English base instructions with FK retry
        english_content, final_grade = await self._generate_english_with_retry(
            discharge_summary
        )

        # Step 3: Build document container
        return PatientInstructionsDocument(
            primary_language=preferred_lang.value,
            primary_content=english_content,
            primary_flesch_kincaid_grade=final_grade,
            translations={},  # Populated by PatientInstructionsTranslator (TASK-004)
            language_fallback=is_fallback,
            requested_language=requested_lang,
        )

    async def _generate_english_with_retry(
        self,
        discharge_summary: DischargeSummarySchema,
    ) -> tuple[PatientInstructionsContent, float]:
        """
        Call Gemini Flash to produce English instructions; retry with simplification prompt
        if FK grade exceeds 6.0.

        Returns:
            Tuple of (PatientInstructionsContent, final_fk_grade).
        """
        prompt_vars = self._build_prompt_vars(discharge_summary)
        content: Optional[PatientInstructionsContent] = None
        grade: float = 0.0

        for attempt in range(1, _MAX_FK_RETRIES + 2):  # attempts: 1, 2, 3
            if attempt == 1:
                prompt_text = _GENERATION_PROMPT.format(
                    **prompt_vars,
                    format_instructions=self._parser.get_format_instructions(),
                )
            else:
                # Simplification re-prompt (US-027 Technical Notes)
                raw_text = self._content_to_text(content)
                prompt_text = ReadingLevelScorer.build_simplify_prompt(raw_text)

            response = await self._llm.ainvoke(prompt_text)
            content = self._parser.parse(response.content)

            # Score the aggregated text
            sections = self._content_to_sections(content)
            grade = self._scorer.aggregate_grade(sections)

            if grade <= 6.0:
                logger.info(
                    "Patient instructions passed FK check: grade=%.2f (attempt %d).",
                    grade,
                    attempt,
                )
                break

            logger.warning(
                "FK grade %.2f > 6.0 on attempt %d — retrying simplification.",
                grade,
                attempt,
            )

        return content, grade

    @staticmethod
    def _build_prompt_vars(summary: DischargeSummarySchema) -> dict:
        """Extract text fields from DischargeSummarySchema for prompt interpolation."""
        diagnoses_text = "; ".join(
            f"{d.icd10_code} – {d.description}"
            for d in (summary.diagnoses or [])
        )
        meds_text = "; ".join(
            f"{m.drug_name} {m.dose} {m.frequency} {m.route}"
            for m in (summary.medications_at_discharge or [])
        )
        procedures_text = "; ".join(
            p.description for p in (summary.procedures or [])
        )
        return {
            "diagnoses": diagnoses_text or "Not specified",
            "medications": meds_text or "None",
            "procedures": procedures_text or "None",
            "follow_up": summary.follow_up_instructions or "Not specified",
            "warning_signs": summary.warning_signs or "Not specified",
            "activity_restrictions": summary.activity_restrictions or "Not specified",
        }

    @staticmethod
    def _content_to_sections(content: PatientInstructionsContent) -> dict[str, str]:
        """Convert PatientInstructionsContent to a flat dict of section_name → text."""
        return {
            "home_care_instructions": content.home_care_instructions,
            "medications": content.medications,
            "warning_signs": content.warning_signs,
            "follow_up_appointments": content.follow_up_appointments,
            "diet_and_activity": content.diet_and_activity,
            "emergency_contact": content.emergency_contact,
        }

    def _content_to_text(self, content: Optional[PatientInstructionsContent]) -> str:
        """Concatenate all sections into a single text block for re-prompting."""
        if content is None:
            return ""
        return "\n\n".join(self._content_to_sections(content).values())
