/**
 * PdfDownloadService — generates HIPAA-compliant discharge instruction PDFs
 * client-side using jsPDF autoTable (US-054).
 *
 * PHI inclusion rules (HIPAA minimum-necessary):
 *   INCLUDED   : first_name, discharge_date, hospital_name
 *   EXCLUDED   : last_name, DOB, MRN, phone, email
 *
 * PDF structure per page:
 *   Header : SmartHandoff logo text + hospital_name + discharge_date
 *   Body   : one autoTable section per instruction category
 *   Footer : "Generated by SmartHandoff — Always contact your care team with questions."
 *
 * Design refs:
 *   US-054 Technical Notes  — jsPDF 2.x, HIPAA minimum-necessary
 *   US-054 Scenario 1       — formatted layout, heading per section, footer text
 *   design.md §3.4          — patient-portal feature module boundary
 */
import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { InstructionContent } from './discharge-instructions.types';

export interface PdfContext {
  /** Patient first name only — HIPAA minimum-necessary. */
  firstName: string;
  /** ISO-8601 discharge date string e.g. "2026-07-14". */
  dischargeDate: string;
  hospitalName: string;
  content: InstructionContent;
}

@Injectable({ providedIn: 'root' })
export class PdfDownloadService {
  private readonly FOOTER_TEXT =
    'Generated by SmartHandoff — Always contact your care team with questions.';

  /**
   * Generates and triggers a browser download of the discharge instructions PDF.
   *
   * @param ctx Patient context object with minimum PHI + instruction content.
   */
  download(ctx: PdfContext): void {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 14;

    this.renderHeader(doc, ctx, pageWidth, margin);
    this.renderSections(doc, ctx.content, margin, pageWidth);
    this.renderFooterOnAllPages(doc, pageWidth, pageHeight);

    const safeName = ctx.firstName.replace(/\s+/g, '_');
    const safeDate = ctx.dischargeDate.replace(/-/g, '');
    doc.save(`SmartHandoff_Discharge_Instructions_${safeName}_${safeDate}.pdf`);
  }

  // ─── Private helpers ────────────────────────────────────────────────────────

  private renderHeader(
    doc: jsPDF,
    ctx: PdfContext,
    pageWidth: number,
    margin: number,
  ): void {
    // Brand header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('SmartHandoff', margin, 20);

    // Subtitle: hospital + date
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(ctx.hospitalName, margin, 28);
    doc.text(`Discharge Date: ${ctx.dischargeDate}`, margin, 34);

    // Title line
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Discharge Instructions for ' + ctx.firstName, margin, 42);

    // Horizontal line separator
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 45, pageWidth - margin, 45);
  }

  private renderSections(
    doc: jsPDF,
    content: InstructionContent,
    margin: number,
    pageWidth: number,
  ): void {
    const contentWidth = pageWidth - 2 * margin;
    let startY = 52;

    // Medications section
    if (content.medications && content.medications.length > 0) {
      const medicationsData = content.medications.map((m) => [
        m.name,
        m.dosage,
        m.frequency,
        m.notes || '-',
      ]);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Your Medications', margin, startY);
      startY += 6;
      autoTable(doc, {
        startY,
        head: [['Medication', 'Dosage', 'Frequency', 'Notes']],
        body: medicationsData,
        margin: margin,
      });
      startY = (doc as any).lastAutoTable.finalY + 5;
    }

    // Activity section
    if (content.activity) {
      startY += 3;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Activity', margin, startY);
      startY += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const splitText = doc.splitTextToSize(content.activity, pageWidth - 2 * margin - 4);
      doc.text(splitText, margin + 2, startY);
      startY += splitText.length * 5;
    }

    // Diet section
    if (content.diet) {
      startY += 3;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Diet', margin, startY);
      startY += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const splitText = doc.splitTextToSize(content.diet, pageWidth - 2 * margin - 4);
      doc.text(splitText, margin + 2, startY);
      startY += splitText.length * 5;
    }

    // Follow-up section
    if (content.follow_up && content.follow_up.length > 0) {
      startY += 3;
      const followUpData = content.follow_up.map((f) => [
        f.provider,
        f.timeframe,
        f.contact || '-',
      ]);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Follow-up Appointments', margin, startY);
      startY += 6;
      autoTable(doc, {
        startY,
        head: [['Provider', 'Timeframe', 'Contact']],
        body: followUpData,
        margin: margin,
      });
      startY = (doc as any).lastAutoTable.finalY + 5;
    }

    // Warning signs section
    if (content.warning_signs && content.warning_signs.length > 0) {
      startY += 3;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(255, 0, 0);
      doc.text('Warning Signs — Seek Immediate Medical Attention', margin, startY);
      doc.setTextColor(0, 0, 0);
      startY += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      content.warning_signs.forEach((sign) => {
        doc.text('• ' + sign, margin + 2, startY);
        startY += 5;
      });
    }
  }

  private renderFooterOnAllPages(
    doc: jsPDF,
    pageWidth: number,
    pageHeight: number,
  ): void {
    const pageCount = (doc as any).internal.pages.length - 1;
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(128, 128, 128);
      doc.text(this.FOOTER_TEXT, pageWidth / 2, pageHeight - 8, { align: 'center' });
    }
  }
}
