/**
 * AiAssistedLabelBannerComponent
 *
 * Presentational component that displays one of two UI states:
 *   1. Yellow "⚠ AI-Assisted — Review Required" warning banner (pending documents)
 *   2. "Approved by [name] on [date]" footer strip (approved documents)
 *
 * US-029 Scenarios 1 & 2.
 * WCAG 2.2 AA: contrast ratio ≥ 4.5:1 for both states.
 */
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnChanges,
  SimpleChanges,
} from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';

export type DocumentStatus = 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED';

@Component({
  selector: 'sh-ai-assisted-label-banner',
  standalone: true,
  imports: [CommonModule, MatIconModule, DatePipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <!-- US-029 Scenario 1: AI-Assisted warning banner (status ≠ APPROVED) -->
    @if (showWarningBanner) {
      <div
        class="ai-assisted-banner"
        role="alert"
        aria-live="polite"
        aria-label="AI-Assisted document — clinician review required before use"
      >
        <mat-icon aria-hidden="true">warning_amber</mat-icon>
        <span>&#9888; AI-Assisted &mdash; Review Required</span>
      </div>
    }

    <!-- US-029 Scenario 2: Approved footer (status = APPROVED) -->
    @if (showApprovedFooter) {
      <div
        class="approved-footer"
        role="status"
        aria-label="Document approved"
      >
        <mat-icon aria-hidden="true">verified</mat-icon>
        <span>
          Approved by
          <strong>{{ reviewedByDisplayName ?? 'Clinician' }}</strong>
          on {{ approvedAt | date: 'mediumDate' }}
        </span>
      </div>
    }
  `,
  styles: [`
    /* US-029 Scenario 1 — yellow warning banner */
    .ai-assisted-banner {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.625rem 1rem;
      background-color: #FFF3CD;   /* WCAG AA: contrast ≥ 4.5:1 against #000 */
      color: #000;
      border-left: 4px solid #FFC107;
      font-weight: 500;
      font-size: 0.875rem;
      border-radius: 0 4px 4px 0;
    }

    /* US-029 Scenario 2 — approved footer strip */
    .approved-footer {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      padding: 0.5rem 1rem;
      background-color: #D4EDDA;   /* WCAG AA: contrast ≥ 4.5:1 against #000 */
      color: #155724;
      border-left: 4px solid #28A745;
      font-size: 0.8125rem;
      border-radius: 0 4px 4px 0;
    }

    mat-icon {
      font-size: 1.125rem;
      height: 1.125rem;
      width: 1.125rem;
    }
  `],
})
export class AiAssistedLabelBannerComponent implements OnChanges {
  /**
   * Whether the document was generated by an AI agent.
   * TRUE for all Documentation Agent outputs (permanent — never reset).
   */
  @Input({ required: true }) aiAssistedLabel!: boolean;

  /** Current document lifecycle status. */
  @Input({ required: true }) documentStatus!: DocumentStatus;

  /** Display name of the approving clinician (from reviewed_by_user.display_name). */
  @Input() reviewedByDisplayName: string | null = null;

  /** UTC timestamp of approval (null until approved). */
  @Input() approvedAt: string | Date | null = null;

  /** Derived: show yellow warning banner. */
  showWarningBanner = false;

  /** Derived: show green approved footer. */
  showApprovedFooter = false;

  ngOnChanges(_changes: SimpleChanges): void {
    // US-029 Scenario 1: banner visible when ai_assisted AND not yet approved
    this.showWarningBanner =
      this.aiAssistedLabel === true && this.documentStatus !== 'APPROVED';

    // US-029 Scenario 2: footer visible only when fully approved
    this.showApprovedFooter = this.documentStatus === 'APPROVED';
  }
}
