"""Patient medication summary schema and models.

Provides the canonical Pydantic v2 output schema for patient-readable medication
change summaries generated by the MedicationSummaryGenerator agent.

Design refs:
    US-033 Definition of Done — Output schema: {"new": [...], "stopped": [...], "changed": [...], "continued": [...]}
    US-033 AC Scenario 1      — sections: new (purpose + dosing + side effects), stopped, changed
    design.md §4.2            — Pydantic v2 validation enforced throughout FastAPI backend
"""
from __future__ import annotations

from app.agents.medication_reconciliation.summary.generator import (
    MedicationSummaryGenerator,
)
from app.agents.medication_reconciliation.summary.schema import (
    ChangedMedicationEntry,
    MedicationEntry,
    MedicationSummaryOutput,
    StoppedMedicationEntry,
)
from app.agents.medication_reconciliation.summary.translator import (
    MedicationSummaryTranslator,
)
from app.agents.medication_reconciliation.summary.writer import (
    MedicationSummaryWriter,
)

__all__ = [
    "MedicationEntry",
    "StoppedMedicationEntry",
    "ChangedMedicationEntry",
    "MedicationSummaryOutput",
    "MedicationSummaryGenerator",
    "MedicationSummaryTranslator",
    "MedicationSummaryWriter",
]
